#import "WL4Session.h"
#import "wl4_config.h"      /* generated by CMake: WL4_EXPECT_CODE */
#include "host.h"

@implementation WL4Session {
    NSData *_lastSaved;
    BOOL _started;
}

+ (instancetype)shared {
    static WL4Session *s;
    static dispatch_once_t once;
    dispatch_once(&once, ^{ s = [WL4Session new]; });
    return s;
}

- (instancetype)init {
    if ((self = [super init])) {
        _documentsPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES).firstObject;
        _romPath = [_documentsPath stringByAppendingPathComponent:@"wl4.gba"];
        _savePath = [_documentsPath stringByAppendingPathComponent:@"wl4.sav"];
        _logPath = [_documentsPath stringByAppendingPathComponent:@"wl4.log"];
    }
    return self;
}

#pragma mark - ROM

/* nil = acceptable Wario Land 4 ROM for the version this app was built from */
static NSString *CheckRom(NSData *d) {
    if (d.length < 0x100000 || d.length > 0x2000000) return @"That doesn't look like a GBA ROM (unexpected file size).";
    char code[5] = {0};
    [d getBytes:code range:NSMakeRange(0xAC, 4)];
    NSString *got = [NSString stringWithFormat:@"%.4s", code];
    if (![got isEqualToString:@WL4_EXPECT_CODE]) {
        return [NSString stringWithFormat:@"Expected Wario Land 4 (%@) but this ROM reports \"%@\".", @WL4_EXPECT_CODE, got];
    }
    return nil;
}

- (BOOL)hasRom {
    NSData *d = [NSData dataWithContentsOfFile:_romPath options:NSDataReadingMappedIfSafe error:nil];
    return d && CheckRom(d) == nil;
}

- (NSString *)importRomData:(NSData *)data {
    NSString *bad = CheckRom(data);
    if (bad) return bad;
    NSError *err = nil;
    if (![data writeToFile:_romPath options:NSDataWritingAtomic error:&err]) return err.localizedDescription;
    if (_started) return @"ROM saved. Restart the app to use it (the running game keeps the old one).";
    return nil;
}

- (void)adoptRomsFromDocuments {
    if ([self hasRom]) return;
    NSFileManager *fm = NSFileManager.defaultManager;
    for (NSString *name in [fm contentsOfDirectoryAtPath:_documentsPath error:nil]) {
        if (![name.pathExtension.lowercaseString isEqualToString:@"gba"] || [name isEqualToString:@"wl4.gba"]) continue;
        NSData *d = [NSData dataWithContentsOfFile:[_documentsPath stringByAppendingPathComponent:name]];
        if (d && [self importRomData:d] == nil) return;
    }
}

#pragma mark - start / save

- (NSString *)startIfNeeded {
    if (wl4_running()) return nil;
    if (_started) return @"The game stopped after an error. Use \"Share log\" and relaunch the app.";
    NSData *rom = [NSData dataWithContentsOfFile:_romPath];
    if (!rom) return @"No ROM selected.";
    NSString *bad = CheckRom(rom);
    if (bad) return bad;
    NSData *save = [NSData dataWithContentsOfFile:_savePath];
    if (save.length) { wl4_load_save(save.bytes, save.length); _lastSaved = save; }
    int rc = wl4_start(rom.bytes, rom.length);      /* copies the ROM */
    if (rc != 0) return [NSString stringWithFormat:@"The core failed to start (code %d).", rc];
    _started = YES;
    [self applyPause];
    [self pushKeys];
    return nil;
}

- (void)persistSave {
    if (!wl4_running()) return;
    static uint32_t scratch[240 * 160];
    if (wl4_copy_frame(scratch) < 30) return;       /* give the game time to set up its SRAM before the first write */
    uint8_t buf[0x10000];
    int n = wl4_read_save(buf);
    NSData *d = [NSData dataWithBytes:buf length:(NSUInteger)n];
    if (_lastSaved && [d isEqualToData:_lastSaved]) return;
    if ([d writeToFile:_savePath options:NSDataWritingAtomic error:nil]) _lastSaved = d;
}

#pragma mark - pause / keys

- (void)applyPause {
    BOOL pause = !(_appActive && _gameVisible) || _userPaused || _interrupted;
    if (wl4_running()) wl4_pause(pause ? 1 : 0);
}
- (void)pushKeys { wl4_set_keys((uint16_t)(_touchKeys | _padKeys)); }

- (void)setAppActive:(BOOL)v { _appActive = v; [self applyPause]; }
- (void)setGameVisible:(BOOL)v { _gameVisible = v; [self applyPause]; }
- (void)setUserPaused:(BOOL)v { _userPaused = v; [self applyPause]; }
- (void)setInterrupted:(BOOL)v { _interrupted = v; [self applyPause]; }
- (void)setTouchKeys:(uint16_t)k { _touchKeys = k; [self pushKeys]; }
- (void)setPadKeys:(uint16_t)k { _padKeys = k; [self pushKeys]; }

@end
