#!/usr/bin/env python3
"""asm/blob_*.s -> one wasm32 assembly file.

`rom_image` is a zero-filled .bss region the size of the ROM (no ROM bytes end up in
the wasm / generated C, so nothing copyrighted is committed or compiled in).  Every
named blob symbol is an alias `rom_image + offset`.  At runtime hal_load_rom() copies
the user's ROM to BOTH 0x08000000 (raw pointers stored inside blobs) and to the
address of rom_image (symbol references from compiled C).

Usage: gen_blobs.py <repo> <out.S> <rom_size> [defined_symbols.txt]
Symbols listed in the optional file (already defined by compiled C data) are skipped.      (assemble with -I<dir containing baserom.gba>)"""
import re, sys
from pathlib import Path
repo, out, romsize = Path(sys.argv[1]), Path(sys.argv[2]), int(sys.argv[3], 0)
skip = set(Path(sys.argv[4]).read_text().split()) if len(sys.argv) > 4 else set()
lines = ['# generated by gen_blobs.py',
         '.section .bss.rom_image,"",@', '.globl rom_image', '.p2align 2', 'rom_image:',
         f'.skip {romsize}', f'.size rom_image, {romsize}']
count = 0
for f in sorted((repo / "asm").glob("blob_*.s")):
    pending = []
    for raw in f.read_text().splitlines():
        s = raw.split("@")[0].strip()
        m = re.match(r"\.global\s+(\w+)", s)
        if m: pending.append(m.group(1)); continue
        m = re.match(r"baserom_blob\s+(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)", s)
        if m:
            a, b = int(m.group(1), 16), int(m.group(2), 16)
            if pending:
                name = pending.pop()
                if name in skip: continue
                lines += [f'.globl {name}', f'.set {name}, rom_image+{a}', f'.size {name}, {b - a}']
                count += 1
out.write_text("\n".join(lines) + "\n")
print(f"{count} blob symbols aliased into rom_image -> {out}")
