#!/usr/bin/env python3
"""asm/data/*.s -> one C file of byte arrays.

The decomp keeps a few small, non-ROM-blob tables in asm/data/*.s (palette-fade amounts/step limits,
demo configurations, ...).  The wasm build never assembled those files, so the symbols stayed undefined
(--allow-undefined -> address 0) and e.g. sPaletteFadeStepLimits[0] read 0: UpdatePaletteFadeStep never
advanced, the file-select fade-in never finished and the screen stayed black.

usage: gen_asm_data.py <repo> <out.c>
"""
import re, sys
from pathlib import Path

repo, out = Path(sys.argv[1]), Path(sys.argv[2])
syms = []                                   # (name, bytearray)
cur = None
def num(t): return int(t.strip(), 0)
def emit(vals, size):
    for v in vals: cur[1].extend((v & ((1 << (8 * size)) - 1)).to_bytes(size, 'little'))
def align(n, fill=0):
    a = 1 << n
    while len(cur[1]) % a: cur[1].append(fill)

for f in sorted((repo / "asm" / "data").glob("*.s")):
    cur = None
    for raw in f.read_text().splitlines():
        line = raw.split('@')[0]
        for stmt in line.split(';'):
            s = stmt.strip()
            if not s: continue
            m = re.fullmatch(r'(\w+):', s)
            if m:
                cur = (m.group(1), bytearray()); syms.append(cur); continue
            if s.startswith(('.include', '.section', '.global', 'baserom_blob')): 
                if s.startswith('baserom_blob'): cur = None
                continue
            if cur is None: continue
            m = re.match(r'\.(byte|2byte|4byte|align)\s+(.*)', s)
            if not m: print('gen_asm_data: skipped', f.name, repr(s)); continue
            kind, args = m.groups()
            if kind == 'align':
                p = [x.strip() for x in args.split(',')]
                align(num(p[0]), num(p[1]) if len(p) > 1 else 0)
            else:
                emit([num(x) for x in args.split(',')], {'byte': 1, '2byte': 2, '4byte': 4}[kind])

with out.open('w') as o:
    o.write('/* generated by gen_asm_data.py from asm/data/*.s */\n')
    for name, data in syms:
        if not data: continue
        o.write(f'const unsigned char {name}[{len(data)}] __attribute__((aligned(4))) = {{{",".join(map(str, data))}}};\n')
print(f'gen_asm_data: {len([1 for _, d in syms if d])} symbols -> {out}')
